### PR TITLE
Fix spelling in src README

### PR DESCRIPTION
**Pull request by robwise**

### CODE REVIEW

**Comment by puzrin** [comment]
That file is autogenerated and replaced on icons change. I guess, your improvements are for this one: https://github.com/fontello/fontello/blob/master/support/font-templates/README.txt

**Comment by robwise** [comment]
Apologies, changes made to that correct file. Should I undo the changes to the auto-generated file, or just leave them as-is?

**Comment by puzrin** [comment]
Not principal. But it's better to squash into single commit with text ~ like "Fixed font README template spelling".

**Comment by puzrin** [comment]
Thanks!

**Pull request merged**
