### PR TITLE
ADD Font Awesome 4.3.0

### PR DESCRIPTION
**Pull request by francoismassart**
Available inside the added zip file export.

### CODE REVIEW

**Comment by Turqueso** [comment]
any news on this?

**Comment by francoismassart** [comment]
No update on this? It's been a month...

**Comment by puzrin** [comment]
@francoismassart Fonts are prepared in different way, via separate repos. https://github.com/fontello/awesome-uni.font i've updated src myself. Will try to update fontello soon and write instruction.

**Comment by puzrin** [comment]
@francoismassart , sorry for delays. Updated FA.

Font updates are not very user friendly. Nut anything better needs Web UI, and i'm not strong in design. Currently fontello's font are prepared in separate repos of  https://github.com/fontello

It seems, i've prepared general instructions in https://github.com/fontello/brandico.font#contributing. In FA sequence is almost the same:

1. Update svg font source
2. run `make dump` to generate diff file
3. Edit `config.yml`
4. run `make dump` again to build icons with proper names
5. run `make dist` to build font & demo.

Feel free to ask me any questions, i will try to reply faster.

I'm closing this PR, since font was updated in different way.

**Pull request closed without merging**
